### ISSUE TITLE
can't run tests, missing dependancies..

### ISSUE THREAD

**Issue by owocki** [allo-protocol/allo-v2#470]
following https://github.com/allo-protocol/allo-v2/blob/main/docs/DEPLOY_STEPS.md yields

```
owocki@local /Users/owocki/Sites/allo-v2~ % bun test                                                                                                                                         (git)-[main] :

bun test v1.0.21 (837cbd60)

lib/openzeppelin-contracts-upgradeable/test/migrate-imports.test.js:
ENOENT: No such file or directory
   errno: -2
 syscall: "access"
   path: "contracts/governance/TimelockControllerUpgradeable.sol"

✗ migrate-imports.js > every new path exists [1.32ms]
✓ migrate-imports.js > replaces import paths in a file [0.55ms]

lib/solady/js/solady.test.js:
[PASS] LibZip: FastLZ compress / decompress.
[PASS] LibZip: Calldata compress / decompress.
[PASS] LibZip: Calldata compress.
[PASS] ERC1967Factory: ABI and address.

lib/openzeppelin-contracts/test/migrate-imports.test.js:
ENOENT: No such file or directory
   errno: -2
 syscall: "access"
   path: "contracts/governance/TimelockControllerUpgradeable.sol"

✗ migrate-imports.js > every new path exists [0.16ms]
✓ migrate-imports.js > replaces import paths in a file [0.32ms]

lib/openzeppelin-contracts-upgradeable/test/proxy/Clones.test.js:
error: Cannot find module "@openzeppelin/test-helpers" from "/Users/owocki/Sites/allo-v2/lib/openzeppelin-contracts-upgradeable/test/proxy/Clones.test.js"

lib/openzeppelin-contracts-upgradeable/test/access/AccessControl.test.js:
error: Cannot find module "@openzeppelin/test-helpers" from "/Users/owocki/Sites/allo-v2/lib/openzeppelin-contracts-upgradeable/test/access/AccessControl.behavior.js"

lib/openzeppelin-contracts-upgradeable/test/access/Ownable2Step.test.js:
error: Cannot find module "@openzeppelin/test-helpers" from "/Users/owocki/Sites/allo-v2/lib/openzeppelin-contracts-upgradeable/test/access/Ownable2Step.test.js"

lib/openzeppelin-contracts-upgradeable/test/access/AccessControlCrossChain.test.js:
error: Cannot find module "@openzeppelin/test-helpers" from "/Users/owocki/Sites/allo-v2/lib/openzeppelin-contracts-upgradeable/test/access/AccessControlCrossChain.test.js"

lib/openzeppelin-contracts-upgradeable/test/access/AccessControlEnumerable.test.js:
error: Cannot find module "@openzeppelin/test-helpers" from "/Users/owocki/Sites/allo-v2/lib/openzeppelin-contracts-upgradeable/test/access/AccessControl.behavior.js"

lib/openzeppelin-contracts-upgradeable/test/access/AccessControlDefaultAdminRules.test.js:
error: Cannot find module "@openzeppelin/test-helpers" from "/Users/owocki/Sites/allo-v2/lib/openzeppelin-contracts-upgradeable/test/access/AccessControlDefaultAdminRules.test.js"

lib/openzeppelin-contracts-upgradeable/test/access/Ownable.test.js:
error: Cannot find module "@openzeppelin/test-helpers" from "/Users/owocki/Sites/allo-v2/lib/openzeppelin-contracts-upgradeable/test/access/Ownable.test.js"

lib/openzeppelin-contracts-upgradeable/test/security/PullPayment.test.js:
error: Cannot find module "@openzeppelin/test-helpers" from "/Users/owocki/Sites/allo-v2/lib/openzeppelin-contracts-upgradeable/test/security/PullPayment.test.js"

lib/openzeppelin-contracts-upgradeable/test/security/Pausable.test.js:
error: Cannot find module "@openzeppelin/test-helpers" from "/Users/owocki/Sites/allo-v2/lib/openzeppelin-contracts-upgradeable/test/security/Pausable.test.js"

lib/openzeppelin-contracts-upgradeable/test/security/ReentrancyGuard.test.js:
error: Cannot find module "@openzeppelin/test-helpers" from "/Users/owocki/Sites/allo-v2/lib/openzeppelin-contracts-upgradeable/test/security/ReentrancyGuard.test.js"

lib/openzeppelin-contracts-upgradeable/test/crosschain/CrossChainEnabled.test.js:
1 | const { promisify } = require('util');
2 | 
3 | const BridgeAMBMock = artifacts.require('BridgeAMBMock');
                          ^
ReferenceError: Can't find variable: artifacts
      at /Users/owocki/Sites/allo-v2/lib/openzeppelin-contracts-upgradeable/test/helpers/crosschain.js:3:23
      at /Users/owocki/Sites/allo-v2/lib/openzeppelin-contracts-upgradeable/test/crosschain/CrossChainEnabled.test.js:1:9

lib/openzeppelin-contracts-upgradeable/test/utils/ShortStrings.test.js:
1 | const { expect } = require('chai');
2 | const { expectRevertCustomError } = require('../helpers/customError');
3 | 
4 | const ShortStrings = artifacts.require('$ShortStrings');
                         ^
ReferenceError: Can't find variable: artifacts
      at /Users/owocki/Sites/allo-v2/lib/openzeppelin-contracts-upgradeable/test/utils/ShortStrings.test.js:4:22

lib/openzeppelin-contracts-upgradeable/test/utils/Strings.test.js:
error: Cannot find module "@openzeppelin/test-helpers" from "/Users/owocki/Sites/allo-v2/lib/openzeppelin-contracts-upgradeable/test/utils/Strings.test.js"

lib/openzeppelin-contracts-upgradeable/test/utils/Checkpoints.test.js:
error: Cannot find module "@openzeppelin/test-helpers" from "/Users/owocki/Sites/allo-v2/lib/openzeppelin-contracts-upgradeable/test/utils/Checkpoints.test.js"

lib/openzeppelin-contracts-upgradeable/test/utils/Context.test.js:
error: Cannot find module "@openzeppelin/test-helpers" from "/Users/owocki/Sites/allo-v2/lib/openzeppelin-contracts-upgradeable/test/utils/Context.test.js"

```

maybe theres a missing setup step in the docs?

**Comment by owocki** [comment]
hmmm `bun run test ` from https://github.com/allo-protocol/allo-v2/blob/main/DEV.md works, so this might just be using a command i dont have?
